/**
 * partnerWriter.ts
 * ----------------
 * Server-side utility (Node.js only) to read and write src/data/partners.ts.
 * Used exclusively by internal admin API routes — never imported by public pages.
 *
 * Strategy:
 *   - READ:  dynamically import partners.ts (already compiled by Next.js) or
 *            read the raw file and strip it to JSON via a regex extraction.
 *   - WRITE: serialize the partners array back into valid TypeScript and
 *            overwrite the file, with an automatic .bak backup first.
 */

import fs from "fs"
import path from "path"
import type { Partner } from "@/src/data/partners"

const PARTNERS_FILE = path.join(process.cwd(), "src/data/partners.ts")
const BACKUP_FILE = path.join(process.cwd(), "src/data/partners.ts.bak")

// ─── READ ────────────────────────────────────────────────────────────────────

/**
 * Returns the current partners array by importing the module at runtime.
 * Next.js dev server keeps modules hot, so this always reflects the latest saved state.
 */
export async function readPartners(): Promise<Partner[]> {
  // Bust the module cache so we always get the latest file
  const mod = await import(`@/src/data/partners?t=${Date.now()}`)
  return mod.partners as Partner[]
}

// ─── WRITE ───────────────────────────────────────────────────────────────────

/**
 * Overwrites src/data/partners.ts with the given partners array.
 * Creates a .bak backup before writing.
 */
export function writePartners(partners: Partner[]): void {
  // Backup
  if (fs.existsSync(PARTNERS_FILE)) {
    fs.copyFileSync(PARTNERS_FILE, BACKUP_FILE)
  }

  const content = generatePartnersTS(partners)
  fs.writeFileSync(PARTNERS_FILE, content, "utf-8")
}

// ─── CODE GENERATOR ──────────────────────────────────────────────────────────

function generatePartnersTS(partners: Partner[]): string {
  const partnerVarNames: string[] = []

  const partnerBlocks = partners
    .map((p) => {
      const varName = slugToVarName(p.id)
      partnerVarNames.push(varName)
      return `const ${varName}: Partner = ${serialize(p)}`
    })
    .join("\n\n")

  return `/**
 * partners.ts
 * -----------
 * Single source of truth for all merch partners.
 * To add a new partner: push a new entry to the \`partners\` array.
 * To update/replace placeholder data: edit the relevant entry below.
 *
 * Asset convention:
 *   /public/partners/<slug>/logo.png
 *   /public/partners/<slug>/banner.png
 *   /public/partners/<slug>/products/<product-id>-front.png
 *   /public/partners/<slug>/products/<product-id>-back.png
 *
 * Falco keeps its existing assets under /public/falco/ unchanged.
 *
 * AUTO-GENERATED by /admin/partners — do not edit manually while dashboard is active.
 */

export interface ProductColor {
    name: string
    value: string
    hex: string
    images: {
        front: string
        back: string
    }
}

export interface ProductSizing {
    [size: string]: string
}

export interface Product {
    id: string
    name: string
    price: number          // numeric ARS
    priceLabel: string     // formatted string for listing cards, e.g. "$65.000"
    colors: ProductColor[]
    sizes: string[]
    category: string
    lifestyleImages: string[]
    /** Optional close-up photo of the stamp/print area (front or back) */
    closeUp?: string
    description: string
    detailedDescription: string
    features: string[]
    sizing: ProductSizing
    brand: string          // display name
    brandValues: string    // short slogan shown on product page
    featured?: boolean
    /** Short description used in the product card grid */
    cardDescription: string
}

export interface Partner {
    id: string             // slug used in URL, e.g. "falco"
    name: string           // display name, e.g. "FALCO"
    slogan: string         // short one-liner
    description: string    // brand story paragraph 1
    values: string         // brand story paragraph 2
    mission: string        // brand story paragraph 3 (bold)
    logo: string           // path to logo shown in brand header and footer
    cardImage?: string     // optional: image shown in /merch listing card (falls back to logo)
    banner: string         // path to banner / watermark image
    instagramUrl?: string  // optional: if set, shows "Seguir" button in brand page
    featured?: boolean     // shows "Destacado" badge on /merch listing
    products: Product[]
}

// ---------------------------------------------------------------------------
// PARTNER DATA
// ---------------------------------------------------------------------------
${partnerBlocks}

// ---------------------------------------------------------------------------
// EXPORTED PARTNERS ARRAY — order determines display in /merch
// ---------------------------------------------------------------------------
export const partners: Partner[] = [${partnerVarNames.join(", ")}]

/** Helper: find a partner by slug */
export function getPartnerById(id: string): Partner | undefined {
    return partners.find((p) => p.id === id)
}

/** Helper: find a product within a partner */
export function getProductById(
    partnerId: string,
    productId: string
): { partner: Partner; product: Product } | undefined {
    const partner = getPartnerById(partnerId)
    if (!partner) return undefined
    const product = partner.products.find((p) => p.id === productId)
    if (!product) return undefined
    return { partner, product }
}
`
}

function slugToVarName(slug: string): string {
  return slug
    .split("-")
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("")
}

function serialize(value: unknown, indent = 0): string {
  if (value === null) return "null"
  if (value === undefined) return "undefined"
  if (typeof value === "string") return JSON.stringify(value)
  if (typeof value === "number" || typeof value === "boolean") return String(value)

  const pad = "    ".repeat(indent + 1)
  const closePad = "    ".repeat(indent)

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]"
    const items = value.map((v) => `${pad}${serialize(v, indent + 1)}`).join(",\n")
    return `[\n${items},\n${closePad}]`
  }

  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, v]) => v !== undefined)
      .map(([k, v]) => {
        // Quote the key if it's not a valid JS identifier (e.g. "Talle único", "S M L")
        const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : JSON.stringify(k)
        return `${pad}${safeKey}: ${serialize(v, indent + 1)}`
      })
    if (entries.length === 0) return "{}"
    return `{\n${entries.join(",\n")},\n${closePad}}`
  }

  return String(value)
}
